jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:13.0-alpine
        env:
          POSTGRES_USER: esanttos
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: dockercompose
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker exec $(docker ps -qf "ancestor=postgres:13.0-alpine") pg_isready; do
            sleep 1
          done

      - name: Initialize database
        run: |
          docker exec $(docker ps -qf "ancestor=postgres:13.0-alpine") /init-db.sh

      - name: Run Migrations
        run: |
          poetry run python manage.py migrate

      - name: Run Tests
        run: |
          poetry run pytest

      - name: Run Linting
        run: |
          poetry run flake8
